config/routes.rb
Rails.application.routes.draw do
  root to: 'brand/posts#index'

  namespace :api do
    resources :posts, only: [:create]
  end

  namespace :admin do
    get 'statistics', to: 'statistics#index'
    resources :posts do
      member do
        get 'publish', to: 'posts#publish'
        get 'unpublish', to: 'posts#unpublish'
      end
      resources :posts, only: %i[new create]
    end
    resources :exercises do
      member do
        get 'practice', to: 'exercises#practice'
      end
      resources :submissions
    end
    resources :cards do
      collection do
        get 'review_all(/:tag)', to: 'cards#review_all'
      end
      member do
        get 'show_front'
        get 'show_back'
        post 'review'
      end
    end
    resources :tags, only: %i[index]
  end

  scope module: 'brand' do
    get 'about', to: 'pages#about'
    get 'til', to: 'pages#til'
    get 'book-notes', to: 'pages#book_notes'
    resources :posts, only: %i[index show], param: :slug do
      get 'preview', on: :member
    end
  end

  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  module Stages
    DRAFT = 'draft'.freeze
    PUBLISHED = 'published'.freeze

    def self.all
      [DRAFT, PUBLISHED]
    end

    def published?
      stage == PUBLISHED
    end
  end

  include Stages

  has_many :posts
  belongs_to :post, optional: true
  alias_attribute :child_posts, :posts
  alias_attribute :parent_post, :post

  has_many :taggings, as: :taggable
  has_many :tags, through: :taggings

  validates_presence_of :title, :content
  validates_presence_of :stage
  validates :stage, inclusion: { in: Stages.all, message: "%{value} is not a valid stage" }

  after_initialize :set_default_stage, if: :new_record?
  before_save :check_parent_post, :set_slug
  before_save :update_published_at, if: :published?

  def publish
    self.stage = Stages::PUBLISHED
  end

  def unpublish
    self.stage = Stages::DRAFT
  end

  def series?
    posts.present?
  end

  def tagged_with?(names)
    tags.any? { |tag| names.include?(tag.name) }
  end

  private

    def update_published_at
      self.published_at ||= Time.now
    end

    def set_default_stage
      self.stage ||= Stages::DRAFT
    end

    def set_slug
      self.slug = title.parameterize
    end

    def check_parent_post
      if (is_self? || is_a_descendent?)
        errors.add(:post_id, :parent_is_descendent, message: 'parent must not be descendent')
        throw :abort
      else
        true
      end
    end

    def is_a_descendent?
      descendent_posts.include? parent_post
    end

    def is_self?
      parent_post&.id == id unless (parent_post&.id.nil? || id.nil?)
    end

  protected

    def descendent_posts
      children = []
      children += Post.where(post_id: id).to_a unless id.nil?
      descendents = []
      children.each do |post|
        descendents += post.descendent_posts
      end
      children + descendents
    end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    def index
      @published_posts = Post.order(published_at: :desc).all.select(&:published?)
      @draft_posts = Post.order(created_at: :desc).all.reject(&:published?)
    end

    def new
      @post = Post.new(post_id: params[:post_id])
    end

    def show
      @post = PostDecorator.new(post: Post.find_by_id!(params[:id]))
    end

    def edit
      @post = Post.find_by_id!(params[:id])
    end

    def update
      @post = Post.find_by_id!(params[:id])
      if @post.update_attributes(
        title: params[:title],
        content: params[:content],
        post_id: params[:post_id],
        tags: tags
      )
        redirect_to admin_posts_path
      else
        render :edit
      end
    end

    def create
      @post = Post.new(title: params[:title], content: params[:content], post_id: params[:post_id])
      if @post.save
        @post.update(tags: tags)
        return redirect_to admin_post_path(id: params[:post_id]) unless params[:post_id].blank?
        redirect_to admin_posts_path
      else
        render :new
      end
    end

    def tags
      return [] unless !params[:tags].blank?
      params[:tags].split(',').map {
        |name| Tag.find_or_create_by(name: name.strip)
      }
    end

    def destroy
      @post = Post.find_by_id!(params[:id])
      @post.destroy
      redirect_to admin_posts_path
    end

    def publish
      post = Post.find_by_id!(params[:id])
      post.publish
      post.save
      redirect_to admin_posts_path
    end

    def unpublish
      post = Post.find_by_id!(params[:id])
      post.unpublish
      post.save
      redirect_to admin_posts_path
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      @post = Post.new(
        title: params[:title],
        content: params[:content],
        stage: params[:stage]
      )
      if @post.save && @post.update(tags: tags)
        render :json => { :id => @post.id }, :status => 201
      end
    end

    def tags
      return [] unless !params[:tags].blank?
      params[:tags].split(',').map {
        |name| Tag.find_or_create_by(name: name.strip)
      }
    end
  end
end

app/controllers/brand/pages_controller.rb
module Brand
  class PagesController < ApplicationController
    layout 'brand'

    def about; end

    def til
      @posts = Post.all.order('published_at DESC').select do |post|
        post.published? && post.tagged_with?('til')
      end
    end

    def book_notes
      @posts = Post.all.order('published_at DESC').select do |post|
        post.published? && post.tagged_with?('book notes')
      end
    end
  end
end

app/controllers/brand/posts_controller.rb
module Brand
  class PostsController < ApplicationController
    layout 'brand'

    def index
      excluded_tag_names = ['til', 'book notes']
      @posts = Post.includes(:tags)
        .where(stage: Post::Stages::PUBLISHED)
        .order('published_at DESC')
        .select { |post| !post.tagged_with?(excluded_tag_names) }
    end

    def show
      @post = PostDecorator.new(post: Post.find_by!(slug: params[:slug], stage: Post::Stages::PUBLISHED))
    end

    def preview
      @post = PostDecorator.new(post: Post.find_by!(slug: params[:slug]))
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/brand/posts/_descendent_posts.html.haml
%ul
  - posts.each do |post|
    %li
      = link_to post.title, post_path(id: post.id)
      = render partial: 'descendent_posts', locals: { posts: post.child_posts.select(&:published?) }

app/views/brand/posts/_preview_descendent_posts.html.haml
%ul
  - posts.each do |post|
    %li
      = link_to post.title, preview_post_path(slug: post.slug)
      = render partial: 'preview_descendent_posts', locals: { posts: post.child_posts }

app/views/brand/posts/index.html.haml
.ht-container
  #primary.content-area
    %main#main.site-main
      - @posts.each_with_index do |post, index|
        %article#post-19.total-hentry.post-19.post.type-post.status-publish.format-standard.category-uncategorized.tag-boat.tag-lake
          .entry-meta.ht-post-info
            %span.entry-date.published.updated
              %span.ht-day=post.published_at.strftime('%d')
              %span.ht-month-year
                = post.published_at.strftime('%B %Y')
          .ht-post-wrapper
            %header.entry-header
              %h2.entry-title
                = link_to post.title, post_path(slug: post.slug)
              .entry-summary
                %p=truncate(post.content, length: 150)
              .entry-readmore
                = link_to "Read More", post_path(slug: post.slug)

app/views/brand/posts/preview.html.haml
%h1{id: 'entry-title'}="#{@post.title} (Preview)"
- if @post.published?
  Published
- else
  Draft
#entry-content=@post.content
%span="Last updated: #{@post.updated_at.strftime("%m/%d/%Y")}"
= link_to 'Edit', edit_admin_post_path(id: @post.id)
- if @post.series?
  - if @post.child_posts.present?
    %h2 Collection
    .descendent_posts
      = render partial: 'preview_descendent_posts', locals: { posts: @post.child_posts }
  - else
    %p No posts have been published for this series yet!

app/views/brand/posts/show.html.haml
#ht-content.ht-site-content.ht-clearfix
  %header.ht-main-header
    .ht-container
      %h1.ht-main-title="#{@post.title}"
      %nav.breadcrumb-trail.breadcrumbs{role: 'navigation',
                                        aria: { label:'Breadcrumbs' },
                                        itemprop:'breadcrumb'}
        %ul
          %meta{name: 'numberOfItems', content: '2'}
          %meta{name: 'itemListOrder', content: 'Ascending'}
          %li.trail-item.trail-begin{itemprop: 'itemListElement', itemscope: '', itemtype: 'http://schema.org/ListItem'}
            %a{href: "#{root_path}", rel: 'home', itemprop: 'item'}
              %span{itemprop: 'name'} Home
            %meta{itemprop: 'position', content:'1'}
          %li.trail-item.trail-begin{itemprop: 'itemListElement', itemscope: '', itemtype: 'http://schema.org/ListItem'}
            %a{href: "#{link_to @post.title, post_path(slug: @post.slug)}", itemprop: 'item'}
              %span{itemprop: 'name'}=@post.title
            %meta{itemprop: 'position', content:'1'}
  .ht-container
    #primary.content-area
      #main.site-main
        %article{id: "post-#{@post.id}"}
          .entry-content
            .entry-meta.ht-post-info
              %span.entry-date.published.updated
                %span.ht-day="#{@post.published_at.strftime("%d")}"
                %span.ht-month-year="#{@post.published_at.strftime("%B %Y")}"
            = @post.content
  - if @post.series?
    - if @post.child_posts.select(&:published?).present?
      %h2 Collection
      .descendent_posts
        = render partial: 'descendent_posts', locals: { posts: @post.child_posts.select(&:published?) }
    - else
      %p No posts have been published for this series yet!