config/routes.rb
Rails.application.routes.draw do
  root to: 'brand/posts#index'

  namespace :api do
    resources :posts, only: [:create]
  end

  namespace :admin do
    get 'statistics', to: 'statistics#index'
    resources :posts do
      member do
        get 'publish', to: 'posts#publish'
        get 'unpublish', to: 'posts#unpublish'
      end
      resources :posts, only: %i[new create]
    end
    resources :exercises do
      member do
        get 'practice', to: 'exercises#practice'
      end
      resources :submissions
    end
    resources :cards do
      collection do
        get 'review_all(/:tag)', to: 'cards#review_all'
      end
      member do
        get 'show_front'
        get 'show_back'
        post 'review'
      end
    end
    resources :tags, only: %i[index]
  end

  scope module: 'brand' do
    get 'about', to: 'pages#about'
    get 'til', to: 'pages#til'
    get 'book-notes', to: 'pages#book_notes'
    resources :posts, only: %i[index show], param: :slug do
      get 'preview', on: :member
    end
  end

  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  module Stages
    DRAFT = 'draft'.freeze
    PUBLISHED = 'published'.freeze

    def self.all
      [DRAFT, PUBLISHED]
    end

    def published?
      stage == PUBLISHED
    end
  end

  include Stages

  has_many :posts
  belongs_to :post, optional: true
  alias_attribute :child_posts, :posts
  alias_attribute :parent_post, :post

  has_many :taggings, as: :taggable
  has_many :tags, through: :taggings

  validates_presence_of :title, :content
  validates_presence_of :stage
  validates :stage, inclusion: { in: Stages.all, message: "%{value} is not a valid stage" }

  after_initialize :set_default_stage, if: :new_record?
  before_save :check_parent_post, :set_slug
  before_save :update_published_at, if: :published?

  def publish
    self.stage = Stages::PUBLISHED
  end

  def unpublish
    self.stage = Stages::DRAFT
  end

  def series?
    posts.present?
  end

  def tagged_with?(names)
    tags.any? { |tag| names.include?(tag.name) }
  end

  private

    def update_published_at
      self.published_at ||= Time.now
    end

    def set_default_stage
      self.stage ||= Stages::DRAFT
    end

    def set_slug
      self.slug = title.parameterize
    end

    def check_parent_post
      if (is_self? || is_a_descendent?)
        errors.add(:post_id, :parent_is_descendent, message: 'parent must not be descendent')
        throw :abort
      else
        true
      end
    end

    def is_a_descendent?
      descendent_posts.include? parent_post
    end

    def is_self?
      parent_post&.id == id unless (parent_post&.id.nil? || id.nil?)
    end

  protected

    def descendent_posts
      children = []
      children += Post.where(post_id: id).to_a unless id.nil?
      descendents = []
      children.each do |post|
        descendents += post.descendent_posts
      end
      children + descendents
    end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    def index
      @published_posts = Post.order(published_at: :desc).all.select(&:published?)
      @draft_posts = Post.order(created_at: :desc).all.reject(&:published?)
    end

    def new
      @post = Post.new(post_id: params[:post_id])
    end

    def show
      @post = PostDecorator.new(post: Post.find_by_id!(params[:id]))
    end

    def edit
      @post = Post.find_by_id!(params[:id])
    end

    def update
      @post = Post.find_by_id!(params[:id])
      if @post.update_attributes(
        title: params[:title],
        content: params[:content],
        post_id: params[:post_id],
        tags: tags
      )
        redirect_to admin_posts_path
      else
        render :edit
      end
    end

    def create
      @post = Post.new(title: params[:title], content: params[:content], post_id: params[:post_id])
      if @post.save
        @post.update(tags: tags)
        return redirect_to admin_post_path(id: params[:post_id]) unless params[:post_id].blank?
        redirect_to admin_posts_path
      else
        render :new
      end
    end

    def tags
      return [] unless !params[:tags].blank?
      params[:tags].split(',').map {
        |name| Tag.find_or_create_by(name: name.strip)
      }
    end

    def destroy
      @post = Post.find_by_id!(params[:id])
      @post.destroy
      redirect_to admin_posts_path
    end

    def publish
      post = Post.find_by_id!(params[:id])
      post.publish
      post.save
      redirect_to admin_posts_path
    end

    def unpublish
      post = Post.find_by_id!(params[:id])
      post.unpublish
      post.save
      redirect_to admin_posts_path
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      @post = Post.new(
        title: params[:title],
        content: params[:content],
        stage: params[:stage]
      )
      if @post.save && @post.update(tags: tags)
        render :json => { :id => @post.id }, :status => 201
      end
    end

    def tags
      return [] unless !params[:tags].blank?
      params[:tags].split(',').map {
        |name| Tag.find_or_create_by(name: name.strip)
      }
    end
  end
end

app/controllers/brand/posts_controller.rb
module Brand
  class PostsController < ApplicationController
    layout 'brand'

    def index
      excluded_tag_names = ['til', 'book notes']
      @posts = Post.includes(:tags)
        .where(stage: Post::Stages::PUBLISHED)
        .order('published_at DESC')
        .select { |post| !post.tagged_with?(excluded_tag_names) }
    end

    def show
      @post = PostDecorator.new(post: Post.find_by!(slug: params[:slug], stage: Post::Stages::PUBLISHED))
    end

    def preview
      @post = PostDecorator.new(post: Post.find_by!(slug: params[:slug]))
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/admin/posts/_descendent_posts.html.haml
%ul
  - posts.each do |post|
    %li
      = link_to post.title, admin_post_path(id: post.id)
      = render partial: 'descendent_posts', locals: { posts: post.child_posts }

app/views/admin/posts/edit.html.haml
%h1 Edit Post
.post-editor{data: { controller: 'editor', post_id: @post.id}}
  - if @post.errors.any?
    - @post.errors.full_messages.each do |msg|
      %p=msg
  = form_tag(admin_post_path, method: 'put')
  = label_tag(:title, "Title", for: 'post-title')
  = text_field_tag(:title, @post.title, id: 'post-title')
  = label_tag(:post_id, 'Parent', for: 'post_id')
  = select_tag(:post_id, options_from_collection_for_select(Post.all.order('created_at DESC'), 'id', 'title', @post.post_id), prompt: 'Select a parent', id: 'post_id')
  = label_tag(:content, "Content", for: 'edit-entry-content')
  = text_area_tag(:content, @post.content, id: 'edit-entry-content')
  = label_tag(:tags, "Tags", for: 'edit-post-tags')
  = text_field_tag(:tags, @post.tags.map(&:name).join(', '), id: 'edit-post-tags' )
  = submit_tag("Save")
  = link_to 'Preview', preview_post_path(slug: @post.slug), method: 'get'
  = link_to 'Delete', admin_post_path(@post), method: 'delete', data: {confirm: 'Are you sure you want to delete?'}
  = link_to 'New Child Post', new_admin_post_post_path(post_id: @post.id), method: 'get', class: 'btn'

app/views/admin/posts/index.html.haml
%h1 Posts
= link_to 'New Post', new_admin_post_path, method: 'get', class: 'btn'
.posts{data: {controller: 'search'}}
  %label
    Search
    %input{type: 'text', data: { target: 'search.key', action: 'keyup->search#filter' }}
  .drafts
    %h2 Drafts
    - if @draft_posts.empty?
      %p No drafts yet!
    %table
      %tbody
        - @draft_posts.each_with_index do |post, index|
          %tr{data: { target: 'search.record', tags: post.tags.map(&:name).join(', '), title: post.title}}
            %td=link_to post.title, edit_admin_post_path(id: post.id)
            - if post.published?
              %td=link_to 'Unpublish', unpublish_admin_post_path(id: post.id), data: {confirm:'Are you sure?'}
            - else
              %td=link_to 'Publish', publish_admin_post_path(id: post.id)
            %td=post.tags.map(&:name).join(', ')
  .published
    %h2 Published
    - if @published_posts.empty?
      %p Nothing published yet!
    %table
      %tbody
        - @published_posts.each_with_index do |post, index|
          %tr{data: { target: 'search.record', tags: post.tags.map(&:name).join(', '), title: post.title}}
            %td=link_to post.title, preview_post_path(slug: post.slug)
            - if post.published?
              %td=link_to 'Unpublish', unpublish_admin_post_path(id: post.id), data: {confirm:'Are you sure?'}
            - else
              %td=link_to 'Publish', publish_admin_post_path(id: post.id)
            %td=post.tags.map(&:name).join(', ')

app/views/admin/posts/new.html.haml
- if @post.parent_post&.id
  %h1="New Child Post for Post #{@post.parent_post.title}"
- else
  %h1 New Post
- if @post.errors.any?
  - @post.errors.full_messages.each do |msg|
    %p=msg
= form_tag(admin_posts_path, method: 'post')
= hidden_field_tag(:post_id, @post.parent_post&.id)
.form-control
  = label_tag(:title, "Title", for: 'edit-entry-title')
  = text_field_tag(:title, nil, id: 'edit-entry-title')
.form-control
  = label_tag(:content, "Content", for: 'edit-entry-content')
  = text_area_tag(:content, nil, id: 'edit-entry-content' )
.form-control
  = label_tag(:tags, "Tags", for: 'edit-entry-tags')
  = text_field_tag(:tags, nil, id: 'edit-entry-tags' )
= submit_tag("Save", class: 'btn')

app/views/admin/posts/show.html.haml
= link_to 'New Child Post', new_admin_post_post_path(post_id: @post.id), method: 'get', class: 'btn'
%h1{id: 'entry-title'}=@post.title
#entry-content=@post.content
.descendent_posts
  = render partial: 'descendent_posts', locals: { posts: @post.child_posts }
%span="Last updated: #{@post.updated_at.strftime("%m/%d/%Y")}"