config/routes.rb
Rails.application.routes.draw do
  root to: 'brand/posts#index'

  namespace :api do
    resources :posts, only: [:create]
  end

  namespace :admin do
    get 'statistics', to: 'statistics#index'
    resources :posts do
      member do
        get 'publish', to: 'posts#publish'
        get 'unpublish', to: 'posts#unpublish'
      end
      resources :posts, only: %i[new create]
    end
    resources :exercises do
      member do
        get 'practice', to: 'exercises#practice'
      end
      resources :submissions
    end
    resources :cards do
      collection do
        get 'review_all(/:tag)', to: 'cards#review_all'
      end
      member do
        get 'show_front'
        get 'show_back'
        post 'review'
      end
    end
    resources :tags, only: %i[index]
  end

  scope module: 'brand' do
    get 'about', to: 'pages#about'
    get 'til', to: 'pages#til'
    get 'book-notes', to: 'pages#book_notes'
    resources :posts, only: %i[index show], param: :slug do
      get 'preview', on: :member
    end
  end

  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
end

app/models/card.rb
class Card < ApplicationRecord
  include SpacedRepetition

  validates_presence_of :front, :back
  has_many :taggings, as: :taggable
  has_many :tags, through: :taggings
end

app/controllers/admin/cards_controller.rb
module Admin
  class CardsController < BaseController
    def index
      @cards = Card.all
      @tags = Tag.all.order('name ASC')
    end

    def new
      @card = Card.new
    end

    def edit
      @card = Card.find_by_id!(params[:id])
    end

    def update
      @card = Card.find_by_id!(params[:id])
        if @card.update_attributes(
          front: params[:front],
          back: params[:back],
          tags: tags
        )
          redirect_to admin_cards_path
        else
          render :edit
        end
    end

    def create
      @card = Card.new(front: params[:front], back: params[:back])
      if @card.save
        @card.update(tags: tags)
        redirect_to admin_cards_path
      else
        render :new
      end
    end

    def tags
      return [] unless !params[:tags].blank?
      params[:tags].split(',').map {
        |name| Tag.find_or_create_by(name: name.strip)
      }
    end

    def review_all
      cards = Card.all.select(&:due_for_review?)
      if params[:tag]
        cards = cards.select do |card|
          card.tags.map(&:name).include?(params[:tag])
        end
      end
      if cards.present?
        review_queue_card_ids = cards.collect(&:id)
        session[:review_queue_card_ids] = review_queue_card_ids
        redirect_to show_front_admin_card_path(id: review_queue_card_ids.first)
      else
        redirect_to admin_cards_path
      end
    end

    def show_front
      @card = Card.find(params[:id])
    end

    def show_back
      @card = CardDecorator.new(card: Card.find(params[:id]))
    end

    def review
      card_id = params[:id].to_i
      score = params[:score].to_i
      card = Card.find(card_id)
      card = card.review_with_performance_score(score)
      card.save

      queue = session[:review_queue_card_ids]
      queue.delete(card_id)
      if card.repeat?(score)
        queue << card_id
      end
      session[:review_queue_card_ids] = queue

      if queue.present?
        redirect_to show_front_admin_card_path(id: queue.first)
      else
        redirect_to admin_cards_path
      end
    end

    def destroy
      @card = Card.find_by_id!(params[:id])
      @card.destroy
      redirect_to admin_cards_path
    end
  end
end

app/helpers/admin/cards_helper.rb
module Admin::CardsHelper
end

app/views/admin/cards/edit.html.haml
- if @card.errors.any?
  - @card.errors.full_messages.each do |msg|
    %p=msg
= form_tag(admin_card_path, method: 'put')
.form-control
  = label_tag(:front, "Front")
  = text_area_tag(:front, @card.front)
.form-control
  = label_tag(:back, "Back", for: 'card_back')
  = text_area_tag(:back, @card.back, id: 'card_back')
.form-control
  = label_tag(:tags, "Tags", for: 'edit-card-tags')
  = text_field_tag(:tags, @card.tags.map(&:name).join(', '), id: 'edit-card-tags' )
= submit_tag("Save")
= link_to 'Delete', admin_card_path(@card), method: 'delete'

app/views/admin/cards/index.html.haml
= link_to 'Review All', '/admin/cards/review_all', method: 'get', class: 'btn'
= link_to 'New Card', new_admin_card_path, method: 'get', class: 'btn'
.cards{data: {controller: 'search'}}
  %h2 Cards
  %label
    Search
    %input{type: 'text', data: { target: 'search.key', action: 'keyup->search#filter' }}
  - if @cards.empty?
    %p No cards yet!
  %table
    %tbody
      - @cards.each_with_index do |card, index|
        %tr{data: { target: 'search.record', tags: card.tags.map(&:name).join(', ')}}
          %td=link_to card.front, edit_admin_card_path(id: card.id)
          - if card.next_due_date.to_datetime.today?
            %td{class: 'due-day'}="(Due today)"
          - elsif card.next_due_date.to_date == Date.tomorrow
            %td{class: 'due-day'}="(Due tomorrow)"
          - else
            %td{class: 'due-day'}="(Due #{card.next_due_date.strftime("%B %d, %Y")})"
          %td=card.tags.map(&:name).join(', ')
  %div.tags
    %h3 Review by tags
    %ul
      - @tags.each do |tag|
        %li= link_to tag.name, "/admin/cards/review_all/#{tag.name}", method: 'get', class: 'btn'

app/views/admin/cards/new.html.haml
- if @card.errors.any?
  - @card.errors.full_messages.each do |msg|
    %p=msg
= form_tag(admin_cards_path, method: 'post')
.form-control
  = label_tag(:front, "Front", for: 'edit-card-title')
  = text_field_tag(:front, nil, id: 'edit-card-title')
.form-control
  = label_tag(:back, "Back", for: 'edit-card-back')
  = text_area_tag(:back, nil, id: 'edit-card-back' )
.form-control
  = label_tag(:tags, "Tags", for: 'edit-card-tags')
  = text_field_tag(:tags, nil, id: 'edit-card-tags' )
= submit_tag("Save", class: 'btn')

app/views/admin/cards/show_back.html.haml
%div{class: 'card-back'}=@card.back
.performance-score
  = button_to 'Perfect!', review_admin_card_path(id: @card.id), method: 'post', params: {score: 5}
  = button_to 'Good but hesitated!', review_admin_card_path(id: @card.id), method: 'post', params: {score: 4}
  = button_to 'O.K but with difficulty!', review_admin_card_path(id: @card.id), method: 'post', params: {score: 3}
  = button_to 'Seemed easy ...', review_admin_card_path(id: @card.id), method: 'post', params: {score: 2}
  = button_to 'Got it wrong but I remember!', review_admin_card_path(id: @card.id), method: 'post', params: {score: 1}
  = button_to 'NOPE', review_admin_card_path(id: @card.id), method: 'post', params: {score: 0}

app/views/admin/cards/show_front.html.haml
%h1{class: 'card-front'}=@card.front
= link_to 'Show back', show_back_admin_card_path(id: @card.id), class: 'show-back'