config/routes.rb
Rails.application.routes.draw do
  root to: 'brand/posts#index'

  namespace :api do
    resources :posts, only: [:create]
  end

  namespace :admin do
    get 'statistics', to: 'statistics#index'
    resources :posts do
      member do
        get 'publish', to: 'posts#publish'
        get 'unpublish', to: 'posts#unpublish'
      end
      resources :posts, only: %i[new create]
    end
    resources :exercises do
      member do
        get 'practice', to: 'exercises#practice'
      end
      resources :submissions
    end
    resources :cards do
      collection do
        get 'review_all(/:tag)', to: 'cards#review_all'
      end
      member do
        get 'show_front'
        get 'show_back'
        post 'review'
      end
    end
    resources :tags, only: %i[index]
  end

  scope module: 'brand' do
    get 'about', to: 'pages#about'
    get 'til', to: 'pages#til'
    get 'book-notes', to: 'pages#book_notes'
    resources :posts, only: %i[index show], param: :slug do
      get 'preview', on: :member
    end
  end

  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Papyrus
    = csrf_meta_tags
    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'utils'
    = javascript_pack_tag 'application'
  %body
    #branding
      #logo
        %a{href: admin_posts_path}
          %span Papyrus
      %ul#navigation
        - if @current_user.present?
          %li= link_to 'Home', admin_posts_path, class: 'admin_index'
          %li= link_to 'Cards', admin_cards_path, class: 'admin_cards'
          %li= link_to 'Statistics', admin_statistics_path, class: 'admin_statistics'
          %li= link_to 'Tags', admin_tags_path, class: 'admin_tags'
      - if @current_user.present?
        = link_to 'Logout', logout_path, id: 'logout-btn'
    - if @current_user.present?
      = link_to 'View Public Site', root_path, id: 'view-public-site'
    #container
      #content
        = yield

app/views/layouts/admin_posts.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Papyrus
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #branding
      #logo
        %span A.LIN
      - if @current_user.present?
        = link_to 'Logout', logout_path
    #container
      #content
        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Papyrus
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #branding
      #logo
        %span A.LIN
      - if @current_user.present?
        = link_to 'Logout', logout_path
    #container
      #content
        = yield

app/views/layouts/brand.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title LINISNIL
    = csrf_meta_tags
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %link{:href => "http://gmpg.org/xfn/11", :rel => "profile"}/
    %title Alan Lin's Blog
    %meta{:content => "noindex,follow", :name => "robots"}/
    %link{:href => "//fonts.googleapis.com", :rel => "dns-prefetch"}/
    %link#animate-css{:href => "https://wp-themes.com/wp-content/themes/total/css/animate.css?ver=1.0", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#font-awesome-css{:href => "https://wp-themes.com/wp-content/themes/total/css/font-awesome.css?ver=4.4.0", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#owl-carousel-css{:href => "https://wp-themes.com/wp-content/themes/total/css/owl.carousel.css?ver=1.3.3", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#nivo-lightbox-css{:href => "https://wp-themes.com/wp-content/themes/total/css/nivo-lightbox.css?ver=1.3.3", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#superfish-css{:href => "https://wp-themes.com/wp-content/themes/total/css/superfish.css?ver=1.3.3", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#total-style-css{:href => "https://wp-themes.com/wp-content/themes/total/style.css?ver=1.0", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    %link#total-fonts-css{:href => "//fonts.googleapis.com/css?family=Pontano+Sans|Oswald:400,700,300&subset=latin,latin-ext", :media => "all", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag 'brand', media: 'all', 'data-turbolinks-track': 'reload'
  %body.home.blog.columns-3.single.single-post{:style => "background-attachment: scroll;", id: controller.action_name}
    #ht-page
      %header#ht-masthead.ht-site-header
        .ht-container.ht-clearfix
          #ht-site-branding
            %h1.ht-site-title
              %a{:href => "/", :rel => "home"} LINISNIL
            %p.ht-site-description
              %a{:href => "/", :rel => "home"} Alan Lin's blog on software
          / .site-branding
          %nav#ht-site-navigation.ht-main-navigation
            .toggle-bar
              %span
            .ht-menu.ht-clearfix{:style => "display: none;"}
              %ul.sf-js-enabled.sf-arrows
                %li.page_item.page-item-1
                  %a{:href => "/til"} Today I Learned
                %li.page_item.page-item-2
                  %a{:href => "/about"} About
            / #ht-site-navigation
        / #ht-masthead
    #ht-content.ht-site-content.ht-clearfix
      = yield